// <auto-generated />
using System;
using ElectronicService.Infrastructure.Postgres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectronicService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(ElectronicDbContext))]
    [Migration("20260723103340_AddCatalogImportAnalysis")]
    partial class AddCatalogImportAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Audit.ProductAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_product_audit_entries_changed_by");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_product_audit_entries_source_id");

                    b.HasIndex("ProductId", "ChangedAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_product_audit_entries_product_history");

                    b.ToTable("product_audit_entries", (string)null);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Characteristics.CharacteristicDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("characteristic_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_characteristic_definitions_data_type_not_none", "\"data_type\" <> 'None'");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Dictionaries.CatalogAssistantDictionarySuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("NormalizedUnknownPhrase")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_unknown_phrase");

                    b.Property<string>("OriginalMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("original_message");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_comment");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("suggested_kind");

                    b.Property<string>("SuggestedTargetCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suggested_target_code");

                    b.Property<string>("SuggestedTargetValue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("suggested_target_value");

                    b.Property<string>("UnknownPhrase")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("unknown_phrase");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_catalog_assistant_dictionary_suggestions_created_at_utc");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_catalog_assistant_dictionary_suggestions_created_by_user_id");

                    b.HasIndex("NormalizedUnknownPhrase")
                        .HasDatabaseName("ix_catalog_assistant_dictionary_suggestions_normalized_unknown_phrase");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_catalog_assistant_dictionary_suggestions_reviewed_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_catalog_assistant_dictionary_suggestions_status");

                    b.ToTable("catalog_assistant_dictionary_suggestions", (string)null);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Dictionaries.CatalogDictionaryTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("NormalizedPhrase")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_phrase");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("phrase");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TargetCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_code");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("target_value");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPhrase")
                        .HasDatabaseName("ix_catalog_dictionary_terms_normalized_phrase");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_catalog_dictionary_terms_status");

                    b.HasIndex("NormalizedPhrase", "Kind", "TargetCode", "TargetValue")
                        .HasDatabaseName("ix_catalog_dictionary_terms_mapping");

                    b.ToTable("catalog_dictionary_terms", (string)null);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<Guid?>("AppliedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by_user_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("ErrorRowsCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_rows_count");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FileSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("file_sha256")
                        .IsFixedLength();

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_type_id");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at_utc");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("RowsCount")
                        .HasColumnType("integer")
                        .HasColumnName("rows_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("ValidRowsCount")
                        .HasColumnType("integer")
                        .HasColumnName("valid_rows_count");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AppliedByUserId");

                    b.HasIndex("FileSha256")
                        .HasDatabaseName("ix_catalog_import_batches_file_sha256");

                    b.HasIndex("ProductTypeId")
                        .HasDatabaseName("ix_catalog_import_batches_product_type");

                    b.HasIndex("RejectedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("CreatedByUserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_catalog_import_batches_creator_date");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_catalog_import_batches_status_date");

                    b.ToTable("catalog_import_batches", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_import_batches_error_rows_count", "\"error_rows_count\" >= 0");

                            t.HasCheckConstraint("ck_catalog_import_batches_file_sha256", "char_length(\"file_sha256\") = 64");

                            t.HasCheckConstraint("ck_catalog_import_batches_file_size", "\"file_size_bytes\" > 0 AND \"file_size_bytes\" <= 10485760");

                            t.HasCheckConstraint("ck_catalog_import_batches_rows_count", "\"rows_count\" >= 0");

                            t.HasCheckConstraint("ck_catalog_import_batches_rows_statistics", "\"valid_rows_count\" + \"error_rows_count\" <= \"rows_count\"");

                            t.HasCheckConstraint("ck_catalog_import_batches_status_not_none", "\"status\" <> 'None'");

                            t.HasCheckConstraint("ck_catalog_import_batches_valid_rows_count", "\"valid_rows_count\" >= 0");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("CharacteristicDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("characteristic_definition_id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("NormalizedSourceHeader")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("normalized_source_header");

                    b.Property<int>("SourceColumnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("source_column_number");

                    b.Property<string>("SourceHeader")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_header");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_kind");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicDefinitionId")
                        .HasDatabaseName("ix_catalog_import_columns_characteristic");

                    b.HasIndex("BatchId", "SourceColumnNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_import_columns_batch_number");

                    b.HasIndex("BatchId", "TargetKind")
                        .HasDatabaseName("ix_catalog_import_columns_batch_target");

                    b.ToTable("catalog_import_columns", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_import_columns_characteristic_mapping", "(\"target_kind\" = 'Characteristic' AND \"characteristic_definition_id\" IS NOT NULL) OR (\"target_kind\" <> 'Characteristic' AND \"characteristic_definition_id\" IS NULL)");

                            t.HasCheckConstraint("ck_catalog_import_columns_confidence", "\"confidence\" >= 0 AND \"confidence\" <= 1");

                            t.HasCheckConstraint("ck_catalog_import_columns_number", "\"source_column_number\" > 0");

                            t.HasCheckConstraint("ck_catalog_import_columns_target_not_none", "\"target_kind\" <> 'None'");

                            t.HasCheckConstraint("ck_catalog_import_columns_unmapped_not_confirmed", "\"target_kind\" <> 'Unmapped' OR \"is_confirmed\" = FALSE");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportFile", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<byte[]>("ContentBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.HasKey("BatchId");

                    b.ToTable("catalog_import_files", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_import_files_content", "octet_length(\"content\") > 0 AND octet_length(\"content\") <= 10485760");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issues_json");

                    b.Property<string>("NormalizedDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_data_json");

                    b.Property<string>("RawDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data_json");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_json");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "RowNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_import_rows_batch_number");

                    b.HasIndex("BatchId", "Status", "RowNumber")
                        .HasDatabaseName("ix_catalog_import_rows_batch_status_number");

                    b.ToTable("catalog_import_rows", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_import_rows_number", "\"row_number\" >= 2");

                            t.HasCheckConstraint("ck_catalog_import_rows_status_not_none", "\"status\" <> 'None'");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Manufacturers.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("product_types", (string)null);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ProductTypes.ProductTypeCharacteristic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacteristicDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("characteristic_definition_id");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_filterable");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsUsedForReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used_for_replacement");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_type_id");

                    b.Property<string>("ReplacementMatchMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("replacement_match_mode");

                    b.Property<int>("ReplacementWeight")
                        .HasColumnType("integer")
                        .HasColumnName("replacement_weight");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicDefinitionId");

                    b.HasIndex("ProductTypeId", "CharacteristicDefinitionId")
                        .IsUnique();

                    b.ToTable("product_type_characteristics", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_type_characteristics_replacement_match_mode_not_none_when_used", "\"is_used_for_replacement\" = false OR \"replacement_match_mode\" <> 'None'");

                            t.HasCheckConstraint("ck_product_type_characteristics_replacement_weight_not_negative", "\"replacement_weight\" >= 0");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_type_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_price_amount_not_negative", "\"price_amount\" >= 0");

                            t.HasCheckConstraint("ck_products_stock_quantity_not_negative", "\"stock_quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Products.ProductAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("normalized_value");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedValue");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("product_aliases", (string)null);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Products.ProductCharacteristic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacteristicDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("characteristic_definition_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicDefinitionId");

                    b.HasIndex("ProductId", "CharacteristicDefinitionId")
                        .IsUnique();

                    b.ToTable("product_characteristic_values", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_characteristic_values_only_one_value_type", "(\r\n    \"value_data_type\" = 'Text'\r\n    AND \"value_text\" IS NOT NULL\r\n    AND \"value_number\" IS NULL\r\n    AND \"value_boolean\" IS NULL\r\n)\r\nOR\r\n(\r\n    \"value_data_type\" = 'Number'\r\n    AND \"value_text\" IS NULL\r\n    AND \"value_number\" IS NOT NULL\r\n    AND \"value_boolean\" IS NULL\r\n)\r\nOR\r\n(\r\n    \"value_data_type\" = 'Boolean'\r\n    AND \"value_text\" IS NULL\r\n    AND \"value_number\" IS NULL\r\n    AND \"value_boolean\" IS NOT NULL\r\n)");

                            t.HasCheckConstraint("ck_product_characteristic_values_value_data_type_not_none", "\"value_data_type\" <> 'None'");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_status_not_none", "\"status\" <> 'None'");

                            t.HasCheckConstraint("ck_users_type_not_none", "\"type\" <> 'None'");
                        });
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Dictionaries.CatalogAssistantDictionarySuggestion", b =>
                {
                    b.HasOne("ElectronicService.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectronicService.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportBatch", b =>
                {
                    b.HasOne("ElectronicService.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AppliedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElectronicService.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectronicService.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElectronicService.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RejectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElectronicService.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportColumn", b =>
                {
                    b.HasOne("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicService.Domain.Catalog.Characteristics.CharacteristicDefinition", null)
                        .WithMany()
                        .HasForeignKey("CharacteristicDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportFile", b =>
                {
                    b.HasOne("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportBatch", null)
                        .WithOne("File")
                        .HasForeignKey("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportFile", "BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportRow", b =>
                {
                    b.HasOne("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ProductTypes.ProductTypeCharacteristic", b =>
                {
                    b.HasOne("ElectronicService.Domain.Catalog.Characteristics.CharacteristicDefinition", null)
                        .WithMany()
                        .HasForeignKey("CharacteristicDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectronicService.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithMany("Characteristics")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Products.Product", b =>
                {
                    b.HasOne("ElectronicService.Domain.Catalog.Manufacturers.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectronicService.Domain.Catalog.ProductTypes.ProductType", null)
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ElectronicService.Domain.Catalog.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("ElectronicService.Domain.Catalog.ValueObjects.ProductArticle", "Article", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("article");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("ElectronicService.Domain.Catalog.ValueObjects.ProductName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("name");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("ElectronicService.Domain.Catalog.ValueObjects.StockQuantity", "StockQuantity", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("stock_quantity");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Article")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("StockQuantity")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Products.ProductAlias", b =>
                {
                    b.HasOne("ElectronicService.Domain.Catalog.Products.Product", null)
                        .WithMany("Aliases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Products.ProductCharacteristic", b =>
                {
                    b.HasOne("ElectronicService.Domain.Catalog.Characteristics.CharacteristicDefinition", null)
                        .WithMany()
                        .HasForeignKey("CharacteristicDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElectronicService.Domain.Catalog.Products.Product", null)
                        .WithMany("Characteristics")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ElectronicService.Domain.Catalog.ValueObjects.CharacteristicValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("ProductCharacteristicId")
                                .HasColumnType("uuid");

                            b1.Property<bool?>("BooleanValue")
                                .HasColumnType("boolean")
                                .HasColumnName("value_boolean");

                            b1.Property<string>("DataType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("value_data_type");

                            b1.Property<decimal?>("NumberValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("value_number");

                            b1.Property<string>("TextValue")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("value_text");

                            b1.HasKey("ProductCharacteristicId");

                            b1.ToTable("product_characteristic_values");

                            b1.WithOwner()
                                .HasForeignKey("ProductCharacteristicId");
                        });

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ImportBatches.CatalogImportBatch", b =>
                {
                    b.Navigation("File")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.ProductTypes.ProductType", b =>
                {
                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("ElectronicService.Domain.Catalog.Products.Product", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Characteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
