using ElectronicService.Core.Auth.Login;
using ElectronicService.Core.Catalog.Assistant.Abstractions;
using ElectronicService.Core.Catalog.Assistant.AskCatalogAssistant;
using ElectronicService.Core.Catalog.Assistant.DictionarySuggestions.ApproveSuggestion;
using ElectronicService.Core.Catalog.Assistant.DictionarySuggestions.CreateSuggestion;
using ElectronicService.Core.Catalog.Assistant.DictionarySuggestions.GetSuggestions;
using ElectronicService.Core.Catalog.Assistant.DictionarySuggestions.RejectSuggestion;
using ElectronicService.Core.Catalog.Assistant.Parsing;
using ElectronicService.Core.Catalog.CharacteristicDefinitions.CreateDefinition;
using ElectronicService.Core.Catalog.CharacteristicDefinitions.DeleteDefinition;
using ElectronicService.Core.Catalog.CharacteristicDefinitions.GetDefinitions;
using ElectronicService.Core.Catalog.CharacteristicDefinitions.UpdateDefinition;
using ElectronicService.Core.Catalog.Dictionaries.AddTerm;
using ElectronicService.Core.Catalog.Dictionaries.GetTerms;
using ElectronicService.Core.Catalog.Dictionaries.SetTermActive;
using ElectronicService.Core.Catalog.ImportBatches.Analysis;
using ElectronicService.Core.Catalog.ImportBatches.AnalyzeCatalogImportBatch;
using ElectronicService.Core.Catalog.ImportBatches.ApplyCatalogImportBatch;
using ElectronicService.Core.Catalog.ImportBatches.BulkUpdateCatalogImportRows;
using ElectronicService.Core.Catalog.ImportBatches.CreateCatalogImportBatch;
using ElectronicService.Core.Catalog.ImportBatches.DeleteCatalogImportBatch;
using ElectronicService.Core.Catalog.ImportBatches.DownloadCatalogImportFile;
using ElectronicService.Core.Catalog.ImportBatches.ExportCatalogImportErrorReport;
using ElectronicService.Core.Catalog.ImportBatches.GetCatalogImportAppliedProducts;
using ElectronicService.Core.Catalog.ImportBatches.GetCatalogImportBatch;
using ElectronicService.Core.Catalog.ImportBatches.GetCatalogImportBatchHistory;
using ElectronicService.Core.Catalog.ImportBatches.GetCatalogImportMapping;
using ElectronicService.Core.Catalog.ImportBatches.GetCatalogImportReviewQueue;
using ElectronicService.Core.Catalog.ImportBatches.GetCatalogImportRows;
using ElectronicService.Core.Catalog.ImportBatches.GetManufacturerGroups;
using ElectronicService.Core.Catalog.ImportBatches.GetMyCatalogImportBatches;
using ElectronicService.Core.Catalog.ImportBatches.GetRowProblemCodes;
using ElectronicService.Core.Catalog.ImportBatches.RejectCatalogImportBatch;
using ElectronicService.Core.Catalog.ImportBatches.RequestCatalogImportChanges;
using ElectronicService.Core.Catalog.ImportBatches.StartCatalogImportReview;
using ElectronicService.Core.Catalog.ImportBatches.SubmitCatalogImportBatch;
using ElectronicService.Core.Catalog.ImportBatches.UpdateCatalogImportMapping;
using ElectronicService.Core.Catalog.ImportBatches.UpdateCatalogImportRow;
using ElectronicService.Core.Catalog.Manufacturers.CreateApprovedAlias;
using ElectronicService.Core.Catalog.Manufacturers.CreateFromUnresolvedPhrase;
using ElectronicService.Core.Catalog.Manufacturers.Management;
using ElectronicService.Core.Catalog.Manufacturers.MarkPhraseAsNoise;
using ElectronicService.Core.Catalog.Manufacturers.PreviewRecognition;
using ElectronicService.Core.Catalog.Metadata.GetManufacturers;
using ElectronicService.Core.Catalog.Metadata.GetProductTypeCharacteristics;
using ElectronicService.Core.Catalog.Metadata.GetProductTypes;
using ElectronicService.Core.Catalog.PriceCalculations.AddCatalogPriceCalculationLine;
using ElectronicService.Core.Catalog.PriceCalculations.ApplyCatalogPriceCalculationImport;
using ElectronicService.Core.Catalog.PriceCalculations.ChangeCatalogPriceCalculationLineQuantity;
using ElectronicService.Core.Catalog.PriceCalculations.CompleteCatalogPriceCalculation;
using ElectronicService.Core.Catalog.PriceCalculations.CreateCatalogPriceCalculation;
using ElectronicService.Core.Catalog.PriceCalculations.GetCatalogPriceCalculation;
using ElectronicService.Core.Catalog.PriceCalculations.GetMyCatalogPriceCalculations;
using ElectronicService.Core.Catalog.PriceCalculations.RemoveCatalogPriceCalculationLine;
using ElectronicService.Core.Catalog.PriceCalculations.RemoveCatalogPriceCalculationManufacturerDiscount;
using ElectronicService.Core.Catalog.PriceCalculations.SearchCatalogPriceCalculationProducts;
using ElectronicService.Core.Catalog.PriceCalculations.SetCatalogPriceCalculationManufacturerDiscount;
using ElectronicService.Core.Catalog.PriceLists.ActivateCatalogPriceList;
using ElectronicService.Core.Catalog.PriceLists.ApplyCatalogPriceListIssueGroup;
using ElectronicService.Core.Catalog.PriceLists.BulkUpdateCatalogPriceListRows;
using ElectronicService.Core.Catalog.PriceLists.GetCatalogPriceList;
using ElectronicService.Core.Catalog.PriceLists.GetCatalogPriceListIssueGroups;
using ElectronicService.Core.Catalog.PriceLists.GetCatalogPriceListRows;
using ElectronicService.Core.Catalog.PriceLists.GetCatalogPriceListVersions;
using ElectronicService.Core.Catalog.PriceLists.ProcessCatalogPriceList;
using ElectronicService.Core.Catalog.PriceLists.SearchCatalogPriceListProducts;
using ElectronicService.Core.Catalog.PriceLists.UpdateCatalogPriceListRow;
using ElectronicService.Core.Catalog.PriceLists.UploadCatalogPriceList;
using ElectronicService.Core.Catalog.ProductNames.Explanation;
using ElectronicService.Core.Catalog.Products.AddAlias;
using ElectronicService.Core.Catalog.Products.ApplyProductTypeMigration;
using ElectronicService.Core.Catalog.Products.Audit;
using ElectronicService.Core.Catalog.Products.GetAuditHistory;
using ElectronicService.Core.Catalog.Products.GetProductById;
using ElectronicService.Core.Catalog.Products.GetProducts;
using ElectronicService.Core.Catalog.Products.GetReplacements;
using ElectronicService.Core.Catalog.Products.PreviewProductTypeMigration;
using ElectronicService.Core.Catalog.Products.RemoveAlias;
using ElectronicService.Core.Catalog.Products.RemoveCharacteristic;
using ElectronicService.Core.Catalog.Products.SearchProducts;
using ElectronicService.Core.Catalog.Products.SearchReplacements;
using ElectronicService.Core.Catalog.Products.SetCharacteristic;
using ElectronicService.Core.Catalog.Products.UpdateGeneralInformation;
using ElectronicService.Core.Catalog.Products.UpdatePrice;
using ElectronicService.Core.Catalog.Products.UpdateStock;
using ElectronicService.Core.Catalog.ProductTypes.AddOptionalCharacteristic;
using ElectronicService.Core.Catalog.ProductTypes.GetAvailableCharacteristicDefinitions;
using ElectronicService.Core.Catalog.ProductTypes.GetCharacteristicSchema;
using ElectronicService.Core.Catalog.ProductTypes.RemoveCharacteristic;
using ElectronicService.Core.Catalog.ProductTypes.SetCharacteristicRequired;
using ElectronicService.Core.Catalog.ProductTypes.Suggestions;
using ElectronicService.Core.Catalog.Recognition;
using ElectronicService.Core.Catalog.Recognition.Abstractions;
using ElectronicService.Core.Catalog.Recognition.Datasets;
using ElectronicService.Core.Catalog.Recognition.Learning;
using ElectronicService.Core.Catalog.Recognition.Management;
using ElectronicService.Core.Catalog.Recognition.Management.CreateProfile;
using ElectronicService.Core.Catalog.Recognition.Management.SetProfileActive;
using ElectronicService.Core.Catalog.Recognition.Management.UpdateProfile;
using ElectronicService.Core.Catalog.Recognition.Preview;
using ElectronicService.Core.Catalog.Recognition.Strategies;
using ElectronicService.Core.Users.BlockUser;
using ElectronicService.Core.Users.CreateManagerUser;
using ElectronicService.Core.Users.CreateRegularUser;
using ElectronicService.Core.Users.CreateTechnicalUser;
using ElectronicService.Core.Users.MakeUserManager;
using ElectronicService.Core.Users.MakeUserRegular;
using ElectronicService.Core.Users.MakeUserTechnical;
using Microsoft.Extensions.DependencyInjection;

namespace ElectronicService.Core;

public static class DependencyInjectionExtensions
{
    public static IServiceCollection AddCore(this IServiceCollection services)
    {
        services.AddScoped<CreateRegularUserCommandHandler>();
        services.AddScoped<CreateTechnicalUserCommandHandler>();
        services.AddScoped<MakeUserTechnicalCommandHandler>();
        services.AddScoped<MakeUserRegularCommandHandler>();
        services.AddScoped<BlockUserCommandHandler>();
        services.AddScoped<GetCatalogProductsQueryHandler>();
        services.AddScoped<GetCatalogProductByIdQueryHandler>();
        services.AddScoped<SearchProductsQueryHandler>();
        services.AddScoped<GetProductReplacementsQueryHandler>();
        services.AddScoped<UpdateProductPriceCommandHandler>();
        services.AddScoped<UpdateProductStockCommandHandler>();
        services.AddScoped<SetProductCharacteristicCommandHandler>();
        services.AddScoped<AddProductAliasCommandHandler>();
        services.AddScoped<GetCatalogProductTypesQueryHandler>();
        services.AddScoped<GetCatalogProductTypeCharacteristicsQueryHandler>();
        services.AddScoped<GetCatalogManufacturersQueryHandler>();
        services.AddScoped<SearchProductReplacementsQueryHandler>();
        services.AddScoped<GetCatalogDictionaryTermsQueryHandler>();
        services.AddScoped<AddCatalogDictionaryTermCommandHandler>();
        services.AddScoped<SetCatalogDictionaryTermActiveCommandHandler>();
        services.AddScoped<AskCatalogAssistantCommandHandler>();
        services.AddScoped<ICatalogCharacteristicRecognitionStrategy, PoleCountRecognitionStrategy>();
        services.AddScoped<ICatalogCharacteristicRecognitionStrategy, BreakingCapacityRecognitionStrategy>();
        services.AddScoped<ICatalogCharacteristicRecognitionStrategy, LeakageCurrentRecognitionStrategy>();
        services.AddScoped<ICatalogCharacteristicRecognitionStrategy, RatedCurrentRecognitionStrategy>();
        services.AddScoped<ICatalogCharacteristicRecognitionStrategy, TripCurveRecognitionStrategy>();
        services.AddScoped<ICatalogCharacteristicRecognitionStrategy, IpRatingRecognitionStrategy>();
        services.AddScoped<ICatalogCharacteristicRecognitionStrategy, BooleanAliasRecognitionStrategy>();
        services.AddScoped<ICatalogProductNameRecognitionService, CatalogProductNameRecognitionService>();
        services.AddSingleton<ICatalogProductNameEvidenceCoverageService, CatalogProductNameEvidenceCoverageService>();
        services.AddScoped<ICatalogImportProductNameExplanationService, CatalogImportProductNameExplanationService>();
        services.AddScoped<ICatalogImportManufacturerRecognitionShadowService, CatalogImportManufacturerRecognitionShadowService>();
        services.AddScoped<ICatalogImportProductTypeAssignmentService, CatalogImportProductTypeAssignmentService>();
        services.AddScoped<ICatalogImportProductTypeSuggestionShadowService, CatalogImportProductTypeSuggestionShadowService>();
        services.AddScoped<ICatalogImportRecognitionShadowService, CatalogImportRecognitionShadowService>();
        services.AddScoped<ICatalogImportRecognitionEnrichmentService, CatalogImportRecognitionEnrichmentService>();
        services.AddScoped<ICatalogImportRecognitionFeedbackCollector, CatalogImportRecognitionFeedbackCollector>();
        services.AddScoped<ICatalogImportRecognitionFeedbackFinalizer, CatalogImportRecognitionFeedbackFinalizer>();
        services.AddScoped<ICatalogRecognitionCandidateAggregator, CatalogRecognitionCandidateAggregator>();
        services.AddScoped<ICatalogRecognitionCandidateSuggestionPromoter, CatalogRecognitionCandidateSuggestionPromoter>();
        services.AddSingleton<ICatalogRecognitionDatasetSplitAssigner, CatalogRecognitionDatasetSplitAssigner>();
        services.AddScoped<ICatalogRecognitionDatasetExporter, CatalogRecognitionDatasetExporter>();
        services.AddScoped<ICatalogRecognitionDatasetBundleExporter, CatalogRecognitionDatasetBundleExporter>();
        services.AddScoped<ICatalogAssistantMessageParser, RuleBasedCatalogAssistantMessageParser>();
        services.AddScoped<CreateCatalogAssistantDictionarySuggestionCommandHandler>();
        services.AddScoped<GetCatalogAssistantDictionarySuggestionsQueryHandler>();
        services.AddScoped<ApproveCatalogAssistantDictionarySuggestionCommandHandler>();
        services.AddScoped<RejectCatalogAssistantDictionarySuggestionCommandHandler>();
        services.AddScoped<LoginCommandHandler>();
        services.AddScoped<UpdateProductGeneralInformationCommandHandler>();
        services.AddScoped<RemoveProductCharacteristicCommandHandler>();
        services.AddScoped<RemoveProductAliasCommandHandler>();
        services.AddScoped<GetCatalogProductTypeCharacteristicSchemaQueryHandler>();
        services.AddScoped<GetAvailableCharacteristicDefinitionsQueryHandler>();
        services.AddScoped<AddOptionalCharacteristicToProductTypeCommandHandler>();
        services.AddScoped<SetProductTypeCharacteristicRequiredCommandHandler>();
        services.AddScoped<RemoveCharacteristicFromProductTypeCommandHandler>();
        services.AddScoped<GetCatalogCharacteristicDefinitionsQueryHandler>();
        services.AddScoped<CreateCharacteristicDefinitionCommandHandler>();
        services.AddScoped<UpdateCharacteristicDefinitionCommandHandler>();
        services.AddScoped<PreviewProductTypeMigrationQueryHandler>();
        services.AddScoped<ProductTypeMigrationPlanner>();
        services.AddScoped<ApplyProductTypeMigrationCommandHandler>();
        services.AddScoped<ProductAuditRecorder>();
        services.AddScoped<GetProductAuditHistoryQueryHandler>();
        services.AddScoped<ProductAuditSnapshotBuilder>();
        services.AddScoped<CreateManagerUserCommandHandler>();
        services.AddScoped<MakeUserManagerCommandHandler>();
        services.AddScoped<CreateCatalogImportBatchCommandHandler>();
        services.AddScoped<CreateCatalogPriceCalculationCommandHandler>();
        services.AddScoped<AddCatalogPriceCalculationLineCommandHandler>();
        services.AddScoped<ApplyCatalogPriceCalculationImportCommandHandler>();
        services.AddScoped<CompleteCatalogPriceCalculationCommandHandler>();
        services.AddScoped<ChangeCatalogPriceCalculationLineQuantityCommandHandler>();
        services.AddScoped<RemoveCatalogPriceCalculationLineCommandHandler>();
        services.AddScoped<SetCatalogPriceCalculationManufacturerDiscountCommandHandler>();
        services.AddScoped<RemoveCatalogPriceCalculationManufacturerDiscountCommandHandler>();
        services.AddScoped<GetCatalogPriceCalculationQueryHandler>();
        services.AddScoped<GetMyCatalogPriceCalculationsQueryHandler>();
        services.AddScoped<SearchCatalogPriceCalculationProductsQueryHandler>();
        services.AddScoped<UploadCatalogPriceListCommandHandler>();
        services.AddScoped<ProcessCatalogPriceListCommandHandler>();
        services.AddScoped<ActivateCatalogPriceListCommandHandler>();
        services.AddScoped<GetCatalogPriceListQueryHandler>();
        services.AddScoped<GetCatalogPriceListIssueGroupsQueryHandler>();
        services.AddScoped<GetCatalogPriceListRowsQueryHandler>();
        services.AddScoped<GetCatalogPriceListVersionsQueryHandler>();
        services.AddScoped<SearchCatalogPriceListProductsQueryHandler>();
        services.AddScoped<UpdateCatalogPriceListRowCommandHandler>();
        services.AddScoped<BulkUpdateCatalogPriceListRowsCommandHandler>();
        services.AddScoped<ApplyCatalogPriceListIssueGroupCommandHandler>();
        services.AddScoped<AnalyzeCatalogImportBatchCommandHandler>();
        services.AddScoped<GetCatalogImportBatchQueryHandler>();
        services.AddScoped<GetCatalogImportRowsQueryHandler>();
        services.AddScoped<GetCatalogImportRowProblemCodesQueryHandler>();
        services.AddScoped<GetCatalogImportManufacturerGroupsQueryHandler>();
        services.AddScoped<ElectronicService.Core.Catalog.ImportBatches.GetRowExplanations.GetCatalogImportRowExplanationsQueryHandler>();
        services.AddScoped<ICatalogImportRowValidator, CatalogImportRowValidator>();
        services.AddScoped<UpdateCatalogImportRowCommandHandler>();
        services.AddScoped<SubmitCatalogImportBatchCommandHandler>();
        services.AddScoped<GetCatalogImportReviewQueueQueryHandler>();
        services.AddScoped<StartCatalogImportReviewCommandHandler>();
        services.AddScoped<RequestCatalogImportChangesCommandHandler>();
        services.AddScoped<RejectCatalogImportBatchCommandHandler>();
        services.AddScoped<ApplyCatalogImportBatchCommandHandler>();
        services.AddScoped<GetMyCatalogImportBatchesQueryHandler>();
        services.AddScoped<DownloadCatalogImportFileQueryHandler>();
        services.AddScoped<DeleteCatalogImportBatchCommandHandler>();
        services.AddScoped<GetCatalogImportMappingQueryHandler>();
        services.AddScoped<UpdateCatalogImportMappingCommandHandler>();
        services.AddScoped<GetCatalogImportBatchHistoryQueryHandler>();
        services.AddScoped<GetCatalogImportAppliedProductsQueryHandler>();
        services.AddScoped<ExportCatalogImportErrorReportQueryHandler>();
        services.AddScoped<DeleteCharacteristicDefinitionCommandHandler>();
        services.AddScoped<BulkUpdateCatalogImportRowsCommandHandler>();
        services.AddScoped<PreviewCatalogProductNameRecognitionQueryHandler>();
        services.AddScoped<CatalogRecognitionProfilePermissionChecker>();
        services.AddScoped<CreateCatalogCharacteristicRecognitionProfileCommandHandler>();
        services.AddScoped<UpdateCatalogCharacteristicRecognitionProfileCommandHandler>();
        services.AddScoped<SetCatalogCharacteristicRecognitionProfileActiveCommandHandler>();
        services.AddScoped<CatalogManufacturerPermissionChecker>();
        services.AddScoped<CreateApprovedManufacturerAliasCommandHandler>();
        services.AddScoped<CreateManufacturerFromUnresolvedPhraseCommandHandler>();
        services.AddScoped<MarkManufacturerPhraseAsNoiseCommandHandler>();
        services.AddScoped<PreviewManufacturerNameRecognitionQueryHandler>();
        services.AddScoped<ICatalogProductTypeSuggestionService, CatalogProductTypeSuggestionService>();
        services.AddScoped<PreviewCatalogProductTypeSuggestionQueryHandler>();


        return services;
    }
}
